# Generated by Django 4.1 on 2024-07-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='localidad',
            field=models.CharField(default='', max_length=100),
        ),
    ]
